codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        # Enforce overall coverage not dropping below baseline by more than threshold
        target: 80%
        threshold: 2%
    patch:
      default:
        # Require reasonably tested changes on each PR
        target: 85%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
